import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ThemeSwitcher from '@/components/common/ThemeSwitcher'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='fixed top-0 z-50 w-full backdrop-blur-xl'>
          <div className='container flex flex-wrap items-center justify-between py-4 xl:max-w-screen-xl'>
            {/* Navbar content */}
            <ThemeSwitcher />
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
